set(CMAKE_SYSTEM_NAME               Generic)
set(CMAKE_SYSTEM_PROCESSOR          arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)

set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_ID GNU)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

# Use the STM32CubeCLT bundled toolchain when available; fall back to PATH.
set(STM32_TOOLCHAIN_PATH "/opt/st/stm32cubeclt_1.22.0/GNU-tools-for-STM32/bin")
if(EXISTS "${STM32_TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}gcc")
    set(TOOLCHAIN_BIN "${STM32_TOOLCHAIN_PATH}/")
else()
    set(TOOLCHAIN_BIN "")
endif()

set(CMAKE_C_COMPILER   ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER       ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY      ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE         ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}size)

set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C   ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
